# Generated by Django 4.1.1 on 2022-09-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cliente",
            name="outro_campo",
            field=models.BooleanField(default=False),
        ),
    ]
